### ISSUE TITLE
MSVC-8.0-XP64 search tests fail

### ISSUE THREAD

**Issue by cholmquist** [mclow/Boost.Algorithm#12]
The first search test fails, the second never terminates (I waited about two minutes or so).

Relevant bjam output as follows:

search_test1.cpp
d:\code\boost_1_46_0\boost/test/impl/execution_monitor.ipp(948) : warning C4535: calling _set_se_translator() requires /EHa
msvc.link bin\search_test1.test\msvc-8.0\debug\link-static\optimization-speed\search_test1.exe
msvc.manifest bin\search_test1.test\msvc-8.0\debug\link-static\optimization-speed\search_test1.exe
testing.capture-output bin\search_test1.test\msvc-8.0\debug\link-static\optimization-speed\search_test1.run
====== BEGIN OUTPUT ======
Running 1 test case...
Pattern is 8, haysstack is 37 chars long; 
unknown location(0): fatal error in "test_main_caller( argc, argv )": C:\Program Files (x86)\Microsoft Visual Studio 8\VC\INCLUDE\xstring(111) : Assertion failed: string iterator not dereferencable

search_test1.cpp(71): last checkpoint

**\* 1 failure detected in test suite "Test Program"

EXIT STATUS: 201 
====== END OUTPUT ======

```
 "bin\search_test1.test\msvc-8.0\debug\link-static\optimization-speed\search_test1.exe"   > "bin\search_test1.test\msvc-8.0\debug\link-static\optimization-speed\search_test1.output" 2>&1
set status=%ERRORLEVEL%
echo. >> "bin\search_test1.test\msvc-8.0\debug\link-static\optimization-speed\search_test1.output"
echo EXIT STATUS: %status% >> "bin\search_test1.test\msvc-8.0\debug\link-static\optimization-speed\search_test1.output"
if %status% EQU 0 (
    copy "bin\search_test1.test\msvc-8.0\debug\link-static\optimization-speed\search_test1.output" "bin\search_test1.test\msvc-8.0\debug\link-static\optimization-speed\search_test1.run"
)
set verbose=0
if %status% NEQ 0 (
    set verbose=1
)
if %verbose% EQU 1 (
    echo ====== BEGIN OUTPUT ======
    type "bin\search_test1.test\msvc-8.0\debug\link-static\optimization-speed\search_test1.output"
    echo ====== END OUTPUT ======
)
exit %status%
```

...failed testing.capture-output bin\search_test1.test\msvc-8.0\debug\link-static\optimization-speed\search_test1.run...
common.mkdir bin\search_test2.test
common.mkdir bin\search_test2.test\msvc-8.0
common.mkdir bin\search_test2.test\msvc-8.0\debug
common.mkdir bin\search_test2.test\msvc-8.0\debug\link-static
common.mkdir bin\search_test2.test\msvc-8.0\debug\link-static\optimization-speed
compile-c-c++ bin\search_test2.test\msvc-8.0\debug\link-static\optimization-speed\search_test2.obj
search_test2.cpp
d:\code\boost_1_46_0\boost/test/impl/execution_monitor.ipp(948) : warning C4535: calling _set_se_translator() requires /EHa
msvc.link bin\search_test2.test\msvc-8.0\debug\link-static\optimization-speed\search_test2.exe
msvc.manifest bin\search_test2.test\msvc-8.0\debug\link-static\optimization-speed\search_test2.exe

**Comment by mclow** [comment]
Which release is MSVC 8.0?
I have access to Visual Studio 2010 (and maybe 2008)

**Comment by cholmquist** [comment]
It's visual Studio 2005.
The default flags for iterator debugging is only default on Visual Studio 2005 I think (it caused performance issues), maybe you could try to enable them in VS 2010 and see if something shows up.

**Comment by cholmquist** [comment]
```
template<typename Container>
void check_one_pointer ( const Container &haystack, const std::string &needle, int expected ) {
    typedef const typename Container::value_type *ptr_type;
    ptr_type hBeg = &*haystack.begin ();
    ptr_type hEnd = &*haystack.end ();
                      ^------------------ Dereference end() iterator
```

**Comment by mclow** [comment]
Thanks.
I can't do that with strings, can I?
The test is assuming contiguous storage.

**Comment by cholmquist** [comment]
fixes search_test1.cpp
//  Check using pointers
    template<typename Container>
    void check_one_pointer ( const Container &haystack, const std::string &needle, int expected ) {
        typedef const typename Container::value_type _ptr_type;
        ptr_type hBeg = haystack.empty() ? 0 : &_haystack.begin ();
        ptr_type hEnd = hBeg + haystack.size();
        ptr_type nBeg = needle.empty() ? 0 : &*needle.begin ();
        ptr_type nEnd = nBeg + needle.size();

I'm not sure the above is strictly legal in c++03, but the test passes at least so the algorithm seems to be fine.

**Comment by mclow** [comment]
Fixed. Thanks!
Commit 1c1fbfaeb69784d9ce7a8ab33991075ac9331948
